project: https://github.com/AudioReach/audioreach-graphmgr

branches:
  master:
    modes:
      blocking:
        headers:
          - service/inc/public/agm/agm_api.h
abi_checks:
  - path: build/usr/lib/libagm.so
